-- =====================================
-- Revenue Analysis
-- =====================================

-- 1. Total Revenue
-- Calculates total revenue excluding cancelled orders, returns, and invalid prices

SELECT
    SUM(Quantity * UnitPrice) AS total_revenue
FROM online_retailraw
WHERE Quantity > 0
AND UnitPrice > 0
AND InvoiceNo NOT LIKE 'C%';


-- 2. Revenue by Country
-- Calculates total revenue generated by each country

SELECT
    Country,
    SUM(Quantity * UnitPrice) AS revenue_by_country
FROM online_retailraw
WHERE Quantity > 0
AND UnitPrice > 0
AND InvoiceNo NOT LIKE 'C%'
GROUP BY Country
ORDER BY revenue_by_country DESC;